# Generated by Django 6.0.2 on 2026-03-14 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_qtd_total_qtd_disponivel_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_emprestados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Emprestados'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_total',
            field=models.IntegerField(default=1, help_text='Total de exemplares do livro na biblioteca.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade total'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
