# Generated by Django 6.0.2 on 2026-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_autor_nome_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
