# Generated by Django 6.0.2 on 2026-03-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, to='livros.autor', verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='livros.categoria', verbose_name='Categorias'),
        ),
    ]
