# Generated by Django 6.0.2 on 2026-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_alter_livro_options_remove_livro_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Imagem'),
        ),
    ]
