# Generated by Django 6.0.2 on 2026-03-14 13:34

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0004_leitor_pontuacao_atual_calculada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[users.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.validate_telefone]),
        ),
    ]
