# Generated by Django 6.0.2 on 2026-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0005_alter_leitor_cpf_alter_leitor_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, help_text='Previsão de devolução; a devolução efetiva ocorre quando devolvido=True.', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
