# Generated by Django 6.0.2 on 2026-03-14 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0007_alter_leitor_email_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, help_text='Previsão de devolução; a devolução efetiva ocorre quando devolvido=True.', null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
