# Generated by Django 6.0.2 on 2026-03-14 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0008_alter_emprestimo_reserva_dates_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
