# Generated by Django 6.0.2 on 2026-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0010_revert_created_updated_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateField(blank=True, help_text='Se não informada, será preenchida automaticamente com data_reserva + 15 dias.', null=True),
        ),
    ]
