# Generated by Django 6.0.2 on 2026-03-15 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0012_leitorrecompensa_through'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leitorrecompensa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='recompensas',
            field=models.ManyToManyField(blank=True, related_name='leitores_resgataram', through='leitor.LeitorRecompensa', through_fields=('leitor', 'recompensa'), to='leitor.recompensa'),
        ),
        migrations.AlterField(
            model_name='leitorrecompensa',
            name='data_resgate',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do resgate'),
        ),
    ]
