from .recompensa import RecompensaListCreateView, RecompensaRetrieveUpdateDestroyView
from .leitor_recompensa import LeitorRecompensaListCreateView, LeitorRecompensaRetrieveUpdateDestroyView
from .leitor import LeitorListCreateView, LeitorRetrieveUpdateDestroyView
from .emprestimo import EmprestimoListCreateView, EmprestimoRetrieveUpdateDestroyView
from .reserva import ReservaListCreateView, ReservaRetrieveUpdateDestroyView
from .cep import CepConsultaView
